/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm;

import modele.Partie;

/**
 *
 * @author Maïlys
 */
public class PannelNouveauCoup extends javax.swing.JPanel {

    /**
     * Creates new form PannelNouveauCoup
     */
    public PannelNouveauCoup() {
        initComponents();
    }
    public PannelNouveauCoup(Partie partie){
        initComponents();
        this.partie1 = partie;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        partie1 = new modele.Partie();
        Coopere = new javax.swing.JLabel();
        Faitdefaut = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Ab = new javax.swing.JLabel();
        FaitDefaut = new javax.swing.JLabel();
        CC = new javax.swing.JButton();
        CD = new javax.swing.JButton();
        DC = new javax.swing.JButton();
        DD = new javax.swing.JButton();

        Coopere.setText("Coopere");

        Faitdefaut.setText("Fait défaut");

        jLabel3.setText("A/B");

        Ab.setText("Coopere");

        FaitDefaut.setText("Fait défaut");

        CC.setText("C/C");
        CC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CCActionPerformed(evt);
            }
        });

        CD.setText("C/D");
        CD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CDActionPerformed(evt);
            }
        });

        DC.setText("D/C");
        DC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DCActionPerformed(evt);
            }
        });

        DD.setText("D/D");
        DD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FaitDefaut)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Ab))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel3)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DC))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DD))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Coopere)
                        .addGap(18, 18, 18)
                        .addComponent(Faitdefaut)))
                .addContainerGap(208, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Coopere)
                    .addComponent(Faitdefaut)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ab)
                    .addComponent(CC)
                    .addComponent(DC))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FaitDefaut)
                    .addComponent(CD)
                    .addComponent(DD))
                .addContainerGap(183, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CCActionPerformed
        partie1.cooperer(true, true);
    }//GEN-LAST:event_CCActionPerformed

    private void CDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CDActionPerformed
        partie1.cooperer(true, false);
    }//GEN-LAST:event_CDActionPerformed

    private void DCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DCActionPerformed
        partie1.cooperer(false, true);
    }//GEN-LAST:event_DCActionPerformed

    private void DDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DDActionPerformed
        partie1.cooperer(false, false);
    }//GEN-LAST:event_DDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ab;
    private javax.swing.JButton CC;
    private javax.swing.JButton CD;
    private javax.swing.JLabel Coopere;
    private javax.swing.JButton DC;
    private javax.swing.JButton DD;
    private javax.swing.JLabel FaitDefaut;
    private javax.swing.JLabel Faitdefaut;
    private javax.swing.JLabel jLabel3;
    private modele.Partie partie1;
    // End of variables declaration//GEN-END:variables
}
